In [8]:
import numpy as np
import os

path1 = os.path.join('/mnt/pami23/yqliu/out_convlstm', 'out1.txt')
# path2 = os.path.join('mnt/pami23/yqliu/out_convlstm', 'out2.txt')

f1 = open(path1,'r+')
# f2 = open(path2,'r')

dic1 = eval(f1.read())   #读取的str转换为字典1
# dic2 = eval(f2.read())   #读取的str转换为字典2

print('convlstm_results1:', dic1)
# print('convlstm_results2:', dic2)

f1.close()
# f2.close()



SyntaxError: invalid syntax (<string>, line 1)

In [6]:
import os

info = {"MAE": 1,
        "MPAE": 2,
        "Ts0.1": 3,
        "Ts1:": 4,
        "Ts10:": 5,
        }

f1 = open(os.path.join('/mnt/pami23/yqliu/out_convlstm', 'out1.txt'), 'a')

f1.write(str(info))

f1.close()



In [9]:
import numpy as np

a = np.random.rand(3,5,6)

a1 = a[:,0:1,:]
print (a1)
print (a1.shape)

a2 = a[:,3:4,:]
print (a2)
print (a2.shape)

aa = np.concatenate((a1,a2),1)

print (aa)
print (aa.shape)



[[[0.75994528 0.93823614 0.03171427 0.47102889 0.34379538 0.35496557]]

 [[0.92416772 0.48422442 0.24866773 0.68350725 0.26867376 0.7812961 ]]

 [[0.20938509 0.21732796 0.22567346 0.22969697 0.11914355 0.1704556 ]]]
(3, 1, 6)
[[[0.35777547 0.84582326 0.99389965 0.03995152 0.80050426 0.84724305]]

 [[0.61960279 0.07969163 0.79062334 0.54945546 0.82530947 0.78412662]]

 [[0.13362745 0.77559372 0.80969737 0.34673847 0.49008645 0.20668972]]]
(3, 1, 6)
[[[0.75994528 0.93823614 0.03171427 0.47102889 0.34379538 0.35496557]
  [0.35777547 0.84582326 0.99389965 0.03995152 0.80050426 0.84724305]]

 [[0.92416772 0.48422442 0.24866773 0.68350725 0.26867376 0.7812961 ]
  [0.61960279 0.07969163 0.79062334 0.54945546 0.82530947 0.78412662]]

 [[0.20938509 0.21732796 0.22567346 0.22969697 0.11914355 0.1704556 ]
  [0.13362745 0.77559372 0.80969737 0.34673847 0.49008645 0.20668972]]]
(3, 2, 6)


In [11]:
b = np.random.rand(3,5)
print (b)


bb = b[1:]

print (bb.shape)
print (bb)


[[0.66497613 0.23492453 0.94465049 0.26890658 0.73690932]
 [0.62387354 0.73566608 0.67037753 0.73838259 0.36324701]
 [0.09988559 0.54601432 0.2883985  0.66309629 0.60327111]]
(2, 5)
[[0.62387354 0.73566608 0.67037753 0.73838259 0.36324701]
 [0.09988559 0.54601432 0.2883985  0.66309629 0.60327111]]


In [ ]:
import numpy as np

cand_l = []
for cand_e in candi_set:
    cand = select_strategy(cand_e.T)
    cand_l.append(cand)
    
# 不要用concatenate或者stack
        
        